apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster2-9e10"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster2-9e10"
  template:
    metadata:
      labels:
        app: "myakscluster2-9e10"
    spec:
      containers:
        - name: "myakscluster2-9e10"
          image: "containerregisrty.azurecr.io/myakscluster2"
          ports:
          - containerPort: 80