on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: containerregisrty.azurecr.io
        username: ${{ secrets.acr_containerregisrty_username }}
        password: ${{ secrets.acr_containerregisrty_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "dockerfile" -t containerregisrty.azurecr.io/myakscluster2:${{ github.sha }} --label dockerfile-path=dockerfile
        docker push containerregisrty.azurecr.io/myakscluster2:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myakscluster2_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myakscluster299fd | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myakscluster299fd`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myakscluster299fd
        container-registry-url: containerregisrty.azurecr.io
        container-registry-username: ${{ secrets.acr_containerregisrty_username }}
        container-registry-password: ${{ secrets.acr_containerregisrty_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myakscluster299fd
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          containerregisrty.azurecr.io/myakscluster2:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth
