# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: 
      - main 
    types: 
      - closed
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  curl_remote_job_jenkins:
    if: github.event.pull_request.merged == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: curl -X POST -L --user admin:1139e7e619c1c9d53d2c14f0086a28a58f http://www.dima.devops4.fun:8081/job/CI-03/build?token=b35c21abce35f41ab4e25128a1a95667
          
  curl_remote_job_azure:
    if: github.event.pull_request.merged == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: trigger azure devops
        env:
          ORG: ${{ secrets.ORG }}
          DEFID: ${{ secrets.DEFID }}
          TEAMPROJECT: ${{ secrets.TEAMPROJECT }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          restApiRunBuild="https://dev.azure.com/$ORG/$TEAMPROJECT/_apis/build/builds?definitionId=$DEFID&api-version=6.1-preview.6"
          B64_PAT=$(printf "%s"":$TOKEN" | base64)
          curl $restApiRunBuild  -X POST -H "Content-Length: 0"  -H "Authorization: Basic ${B64_PAT}"
